[package]
name = "es8311"
version = "0.1.0"
authors = ["QuackHack-McBlindy"]
license = "MIT"
description = "ES8311 Audio COdec no_std library"
repository = "https://github.com/QuackHack-McBlindy/es8311-rs"
readme = "README.md"
keywords = ["esp-hal", "embedded", "esp32"]
categories = ["development-tools::embedded"]
edition = "2024"

[dependencies]

